### ISSUE TITLE
Softbody with Spring Based

### ISSUE THREAD

**Issue by Adhil-Suresh** [henryclever/FleX_PyBind11#3]
Is it possible to create softbodies with spring based not with bones

**Comment by henryclever** [comment]
I'm sorry, I don't understand the question. Can you please rephrase it?

Henry

**Comment by Adhil-Suresh** [comment]
Actually in flex we can create softbody with particles and shapes. i need to create softbody with spring constraints
https://www.youtube.com/watch?v=7PxWbHDTgVg
i would like to achieve this kind of effect show in video from(0.55 to 1.05) 
There are three ways to create deformable soft body you can see in the link
http://developer.download.nvidia.com/assets/gameworks/downloads/regular/events/cgdc15/Making%20Your%20Game%20Fully%20Interactive%20by%20NVIDIA%20FleX-ENG.pdf
i would like to create softbody using the first two method
• Tetrahedral meshes -> mass
spring system
• Tetrahedral volume
constraints
Do you know how to create that????

**Comment by henryclever** [comment]
Hi,
My guess is that you would build the deformable object so that once two spring-connected particles are separated beyond some distance threshold, the spring is removed (irreversibly). There's also an NvFlex cloth tearing extension, which perhaps could be extended into 3D. But I haven't played with it. 

You can also try posting this in the [main Nvidia branch](https://github.com/NVIDIAGameWorks/FleX) issues page.

Henry C.
